apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeguardian-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeguardian
  template:
    metadata:
      labels:
        app: codeguardian
    spec:
      containers:
      - name: codeguardian-container
        image: gcr.io/scannermodel/codeguardian:v4
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: codeguardian-service
spec:
  selector:
    app: codeguardian
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer

